### ISSUE TITLE
example build failed

### ISSUE THREAD

**Issue by stormagain** [flutterkit/zerker#2]
miss ImageStreamListener、TextWidthBasis and so on

**Comment by drawcall** [comment]
I run it locally, no problem. 

```
➜  example flutter run
Launching lib/main.dart on iPhone Xʀ in debug mode...
Running Xcode build...
 ├─Assembling Flutter resources...                           1.1s
 └─Compiling, linking and signing...                         4.9s
Xcode build done.                                            7.6s
```

If your project missing an `ios/Runner/Info.plist`. running `flutter create .` to create one. Of course you can also run `flutter doctor` to find more questions.

**Comment by stormagain** [comment]
I've tried what you said.

Compiler message:
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/utils/imgloader.dart:31:5: Error: 'ImageStreamListener' isn't a
type.
    ImageStreamListener listener;
    ^^^^^^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/utils/imgloader.dart:56:20: Error: Method not found:
'ImageStreamListener'.
    listener = new ImageStreamListener(onLoadHandler, onError: onErrorHandler);
                   ^^^^^^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/utils/imgloader.dart:56:39: Error: Too many positional arguments:
0 allowed, but 1 found.
Try removing the extra positional arguments.
    listener = new ImageStreamListener(onLoadHandler, onError: onErrorHandler);
                                      ^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:117:7: Error: Type 'TextWidthBasis' not found.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
      ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:153:7: Error: Type 'TextWidthBasis' not found.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
      ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:117:38: Error: Getter not found: 'TextWidthBasis'.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
                                     ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:117:7: Error: 'TextWidthBasis' isn't a type.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
      ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:153:38: Error: Getter not found: 'TextWidthBasis'.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
                                     ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:153:7: Error: 'TextWidthBasis' isn't a type.
      TextWidthBasis textWidthBasis: TextWidthBasis.parent}) {
      ^^^^^^^^^^^^^^
file:///Users/liujian/flutter/flutter/.pub-cache/hosted/pub.dartlang.org/zerker-
1.3.2/lib/src/node/text.dart:160:14: Error: The setter 'textWidthBasis' isn't
defined for the class 'TextPainter'.
 - 'TextPainter' is from 'package:flutter/src/painting/text_painter.dart'
 ('file:///Users/liujian/flutter/flutter/packages/flutter/lib/src/painting/text_
 painter.dart').
Try correcting the name to the name of an existing setter, or defining a setter
or field named 'textWidthBasis'.
    _painter.textWidthBasis = textWidthBasis;
             ^^^^^^^^^^^^^^
Compiler failed on /Users/liujian/Downloads/zerker-samples-master/sprite_demo/lib/main.dart
Error launching application on iPhone 11 Pro Max.

**Comment by stormagain** [comment]
ImageStreamListener is surely undefined.

you can not find it in [https://github.com/flutterkit/zerker/blob/master/lib/src/utils/imgloader.dart](url)

and it's imports

**Comment by drawcall** [comment]
What is your version of flutter? Update to flutter 1.8+, run:

```
flutter upgrade
```

**Comment by stormagain** [comment]
1.5.4 .  

I see , thank you !
