### ISSUE TITLE
How to dispose zerker?

### ISSUE THREAD

**Issue by AuMaHub** [flutterkit/zerker#4]
```
class _MyHomePageState extends State<MyHomePage> {
  Zerker a;
  MyZKApp app = MyZKApp();
  @override
  void initState() {
    super.initState();
    a = Zerker(
        app: app, clip: true, interactive: true, width: 350, height: 350);
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
        appBar: AppBar(
          title: Text(widget.title),
          actions: [
            InkWell(
              child: Text('dispose'),
              onTap: () {
                a = null;
                app.dispose();
                setState(() {});
              },
            )
          ],
        ),
        body: Center(
          child: a,
        ));
  }
}
```

I used the example with some modifications.

![image](https://user-images.githubusercontent.com/48949226/110897070-1a75b780-8340-11eb-9bef-a7dc748fd62e.png)

My computer is a poorly performing device, but my cell phone is worse. If the zerker is not dispose, the performance of the cell phone is very poor.
This cannot be solved with super.dispose.

Please provide me a solution.

**Comment by drawcall** [comment]
Oh, no need to manually dispose ZKApp. I have called it in the `void detach() ` method of zerkerwidget, don't call repeatedly.

```dart
a = null;
// app.dispose();
```

https://github.com/flutterkit/zerker/blob/master/lib/src/zerkerwidget.dart

**Comment by AuMaHub** [comment]
As you say i solved the problem by removing app.dispose().

Thank you!
